### ISSUE TITLE
elem.in 接受字符串数组，生成的代码编译不过

### ISSUE THREAD

**Issue by morefreeze** [cloudwego/protoc-gen-validator#2]
**Describe the bug**

```proto
repeated string standard_envs = 1 [
    (api.vt).elem = {
      in: ["a"]
    }
];
```
按文档执行生成
```bash
hz new -I={$INCLUDEPATH} \ 
       -idl={$IDLPATH} \
       -protoc-plugins=validator:hz=true,go_mod={$GOMODULE}:.
       -mod={$GOMODULE}
```
生成的xxx.pb.go大概常这样
```go
for i := 0; i < len(m.GetStandardEnvs()); i++ {
		_elem := m.GetStandardEnvs()[i]
		_src1 := [][]string{[]string("a")} // 应该是[]string{"a"}

		var _exist1 bool
		for _, src := range _src1 {
			if _elem == src {
				_exist1 = true
				break
			}
		}
		if !_exist1 {
			return fmt.Errorf("field _elem in rule failed, current value: %v", _elem)
		}
	}
```

**To Reproduce**

**Expected behavior**

预期生成文件可以编译通过且支持数组元素校验

**Screenshots**
![image](https://github.com/cloudwego/protoc-gen-validator/assets/1477233/3f4a953a-e76d-49c9-812b-7d27ae6e515e)

<img width="738" alt="image" src="https://github.com/cloudwego/protoc-gen-validator/assets/1477233/02fd02db-b1f7-47e6-bcc1-a400169f692d">

**Kitex version:**

**Environment:**

```
GOARCH="amd64"
GOVERSION="go1.17.13"

```

**Additional context**

**Comment by FGYFFFF** [comment]
感谢反馈，我来 check 下

**Comment by FGYFFFF** [comment]
目前 "repeated" 不支持 "in" 规则，代码里没做拦截，readme/example 里有不同字段对应的规则。不过既然你使用了，我稍后加一个这个能力。

**Comment by morefreeze** [comment]
> 目前 "repeated" 不支持 "in" 规则，代码里没做拦截，readme/example 里有不同字段对应的规则。不过既然你使用了，我稍后加一个这个能力。

辛苦老哥！需求是我要对repeated string 限制每个元素只在一个集合里

**Comment by FGYFFFF** [comment]
修复了下，可以试一下 `go install github.com/cloudwego/protoc-gen-validator@latest`，没啥问题，我下午可以发一个小版本

**Comment by morefreeze** [comment]
好了 感谢光速支持
