### ISSUE TITLE
example中的demo编译报错

### ISSUE THREAD

**Issue by lafer-fz** [cloudwego/protoc-gen-validator#3]
example中的demo编译时报错，
![d23b12ea-270d-4739-aa03-506258cd5397](https://github.com/cloudwego/protoc-gen-validator/assets/42789804/1172d0c5-88d0-45c2-b423-8ccb41e0a044)
原因是生成的api.pb.fast.go存在问题。
api.proto 用的是proto2语法， Fastpb目前只支持proto3语法

**Comment by FGYFFFF** [comment]
可以把 `syntax = "proto2";` 换成 `syntax = "proto3";` 然后可以把一些语法不兼容的地方修改下，不过好像都是兼容的。
